-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 12:30:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `models` (
  `model_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL COMMENT 'Model, begins with the manufacturers name, use - not spaces in name',
  `is_color` TINYINT NOT NULL DEFAULT 0 COMMENT 'Boolean  If 1, it is a color printer, if 0 it is black and white',
  `data_collection_method` VARCHAR(16) NULL COMMENT 'This the method that is used to query the printer to find out toner level and status',
  PRIMARY KEY (`model_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `printers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `printers` (
  `printer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mac_address` CHAR(17) NOT NULL,
  `ip_address` VARCHAR(15) NULL COMMENT 'Several printers can have the same ip_address, but no more than one should be active',
  `model_id` INT UNSIGNED NOT NULL,
  `tag_number` VARCHAR(10) NULL COMMENT 'example: 429-3456',
  `room` VARCHAR(32) NULL COMMENT 'The room where it is installed',
  `is_monitored` TINYINT NOT NULL COMMENT 'There is a monitoring method for this printer',
  `is_active` TINYINT NOT NULL DEFAULT 1 COMMENT 'Boolean: is this printer still active and being used',
  PRIMARY KEY (`printer_id`),
  UNIQUE INDEX `mac_address_UNIQUE` (`mac_address` ASC) VISIBLE,
  UNIQUE INDEX `tag_number_UNIQUE` (`tag_number` ASC) VISIBLE,
  INDEX `fk_printers_models_model_id_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_printers_models_model_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `models` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `color_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `color_levels` (
  `printer_id` INT UNSIGNED NOT NULL,
  `collect_time` DATETIME NOT NULL,
  `color` ENUM("black", "magenta", "yellow", "cyan") NOT NULL,
  `percent_full` INT NULL COMMENT 'Percent full',
  PRIMARY KEY (`printer_id`, `collect_time`, `color`),
  CONSTRAINT `fk_color_levels_printers_printer_id`
    FOREIGN KEY (`printer_id`)
    REFERENCES `printers` (`printer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `install_preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `install_preferences` (
  `room` INT NOT NULL,
  `printer_id` INT UNSIGNED NOT NULL,
  `auto_install` TINYINT NULL DEFAULT 1 COMMENT 'Boolean: Should the cloning process install the requested printer.',
  `comments` VARCHAR(1024) NULL COMMENT 'Teacher may have some reason for what they have requested',
  PRIMARY KEY (`room`, `printer_id`),
  INDEX `fk_install_preferences_printers_printer_id_idx` (`printer_id` ASC) VISIBLE,
  CONSTRAINT `fk_install_preferences_printers_printer_id`
    FOREIGN KEY (`printer_id`)
    REFERENCES `printers` (`printer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `change_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `change_log` (
  `printer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `change_time` TIMESTAMP NOT NULL,
  `mac_address` CHAR(17) NOT NULL,
  `ip_address` VARCHAR(15) NULL,
  `model_id` INT UNSIGNED NOT NULL,
  `tag_number` VARCHAR(10) NULL,
  `name` VARCHAR(45) NULL,
  `room` VARCHAR(32) NULL,
  PRIMARY KEY (`printer_id`),
  UNIQUE INDEX `mac_address_UNIQUE` (`mac_address` ASC) VISIBLE,
  UNIQUE INDEX `tag_number_UNIQUE` (`tag_number` ASC) VISIBLE,
  INDEX `fk_change_log_models_model_id_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_change_log_printers_printer_id`
    FOREIGN KEY (`printer_id`)
    REFERENCES `printers` (`printer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_change_log_models_model_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `models` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `statuses` (
  `printer_id` INT UNSIGNED NOT NULL,
  `collect_time` DATETIME NOT NULL,
  `status` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`printer_id`, `collect_time`, `status`),
  CONSTRAINT `fk_statuses_printers_printer_id`
    FOREIGN KEY (`printer_id`)
    REFERENCES `printers` (`printer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
